[package]
name = "this-report"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["tedius"]
license = "MIT"
description = "Just a template for a lab report"
repository = "https://github.com/tedius-git/this-report"
keywords = [
    "template",
    " lab report",
    " uni",
]

[tool.utpm]
namespace = "local"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
